### ISSUE TITLE
Navigation bar

### ISSUE THREAD

**Issue by Melanie-Koller** [elan-ev/opencast-editor#352] opened 2021-06-04 06:17 UTC
If it is possible to zoom the video, there should be a navigation bar.
![Bildschirmfoto 2021-06-04 um 08 15 26](https://user-images.githubusercontent.com/57887263/120754677-4f437600-c50d-11eb-8a3b-2dc204f46591.jpg)

**Comment by Arnei** [comment] 2021-06-04 07:01
Duplicate of #107. Well, more like an addition to it.

**Closed** 2021-06-07 13:34 UTC
Labels: duplicate
